// Banco de Lectura - Preguntas ICFES (40 preguntas, 8 bancos)
// Formato: Cada banco comparte un contexto de lectura largo (200-400 palabras)

QUESTIONS.push(
    {
        id: 'BL01Q1', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'media',
        bankId: 'BL01', bankQuestion: 1,
        context: `El cambio clim\u00e1tico constituye una de las amenazas m\u00e1s significativas para los ecosistemas colombianos. Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos frente al aumento de las temperaturas globales. Seg\u00fan el IDEAM, las temperaturas medias en el pa\u00eds han aumentado aproximadamente 0,4\u00b0C en las \u00faltimas d\u00e9cadas, una tendencia que se acelera progresivamente. Este fen\u00f3meno tiene consecuencias directas sobre los glaciares de monta\u00f1a, que han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX. Los ecosistemas de p\u00e1ramo, \u00fanicos en el mundo y hogar de especies como el oso de anteojos y la frailej\u00f3n, sufren una contracci\u00f3n notable de su \u00e1rea de distribuci\u00f3n. Adem\u00e1s, el patr\u00f3n de precipitaciones se ha alterado significativamente: algunas regiones experimentan sequ\u00edas m\u00e1s prolongadas mientras otras enfrentan inundaciones m\u00e1s frecuentes. Los cient\u00edicos colombianos han identificado que las comunidades rurales e ind\u00edgenas son especialmente vulnerables, ya que dependen directamente de los recursos naturales para su subsistencia. El Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC) ha se\u00f1alado que Am\u00e9rica Latina y el Caribe son una de las regiones m\u00e1s susceptibles a estos efectos. En respuesta, Colombia ha implementado pol\u00edticas como la Estrategia Nacional de Cambio Clim\u00e1tico y ha participado activamente en negociaciones internacionales. Sin embargo, los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos. La investigaci\u00f3n cient\u00edfica contin\u00faa siendo fundamental para comprender la magnitud del problema y disenar estrategias de adaptaci\u00f3n efectivas que protejan tanto a las poblaciones humanas como a la biodiversidad \u00fanica del pa\u00eds.`,
        question: '\u00bfCu\u00e1l es la raz\u00f3n principal por la cual Colombia es especialmente vulnerable al cambio clim\u00e1tico?',
        options: ['Su ubicaci\u00f3n ecuatorial y enorme biodiversidad', 'Su gran extensi\u00f3n territorial y poblaci\u00f3n densa', 'Su desarrollo industrial avanzado y emisiones elevadas', 'Su ubicaci\u00f3n en el cintur\u00f3n de fuego del Pac\u00edfico'],
        correct: 0,
        explanation: { correct: 'El texto se\u00f1ala que Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos.', wrongs: ['El texto no menciona la extensi\u00f3n territorial.', 'El texto no habla del desarrollo industrial.', 'El cintur\u00f3n de fuego no es mencionado.'] }
    },
    {
        id: 'BL01Q2', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'dificil',
        bankId: 'BL01', bankQuestion: 2,
        context: `El cambio clim\u00e1tico constituye una de las amenazas m\u00e1s significativas para los ecosistemas colombianos. Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos frente al aumento de las temperaturas globales. Seg\u00fan el IDEAM, las temperaturas medias en el pa\u00eds han aumentado aproximadamente 0,4\u00b0C en las \u00faltimas d\u00e9cadas, una tendencia que se acelera progresivamente. Este fen\u00f3meno tiene consecuencias directas sobre los glaciares de monta\u00f1a, que han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX. Los ecosistemas de p\u00e1ramo, \u00fanicos en el mundo y hogar de especies como el oso de anteojos y la frailej\u00f3n, sufren una contracci\u00f3n notable de su \u00e1rea de distribuci\u00f3n. Adem\u00e1s, el patr\u00f3n de precipitaciones se ha alterado significativamente: algunas regiones experimentan sequ\u00edas m\u00e1s prolongadas mientras otras enfrentan inundaciones m\u00e1s frecuentes. Los cient\u00edicos colombianos han identificado que las comunidades rurales e ind\u00edgenas son especialmente vulnerables, ya que dependen directamente de los recursos naturales para su subsistencia. El Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC) ha se\u00f1alado que Am\u00e9rica Latina y el Caribe son una de las regiones m\u00e1s susceptibles a estos efectos. En respuesta, Colombia ha implementado pol\u00edticas como la Estrategia Nacional de Cambio Clim\u00e1tico y ha participado activamente en negociaciones internacionales. Sin embargo, los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos. La investigaci\u00f3n cient\u00edfica contin\u00faa siendo fundamental para comprender la magnitud del problema y disenar estrategias de adaptaci\u00f3n efectivas que protejan tanto a las poblaciones humanas como a la biodiversidad \u00fanica del pa\u00eds.`,
        question: '\u00bfQu\u00e9 evidencia cuantitativa presenta el texto sobre el impacto del cambio clim\u00e1tico en los glaciares?',
        options: ['Han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX', 'Se han reducido en un 25% en los \u00faltimos 30 a\u00f1os', 'Han desaparecido completamente en tres regiones', 'Han aumentado su volumen debido al aumento de precipitaciones'],
        correct: 0,
        explanation: { correct: 'El texto afirma que los glaciares han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX.', wrongs: ['El 25% no es la cifra mencionada.', 'El texto no indica desaparici\u00f3n completa.', 'El texto describe contracci\u00f3n, no aumento.'] }
    },
    {
        id: 'BL01Q3', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'media',
        bankId: 'BL01', bankQuestion: 3,
        context: `El cambio clim\u00e1tico constituye una de las amenazas m\u00e1s significativas para los ecosistemas colombianos. Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos frente al aumento de las temperaturas globales. Seg\u00fan el IDEAM, las temperaturas medias en el pa\u00eds han aumentado aproximadamente 0,4\u00b0C en las \u00faltimas d\u00e9cadas, una tendencia que se acelera progresivamente. Este fen\u00f3meno tiene consecuencias directas sobre los glaciares de monta\u00f1a, que han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX. Los ecosistemas de p\u00e1ramo, \u00fanicos en el mundo y hogar de especies como el oso de anteojos y la frailej\u00f3n, sufren una contracci\u00f3n notable de su \u00e1rea de distribuci\u00f3n. Adem\u00e1s, el patr\u00f3n de precipitaciones se ha alterado significativamente: algunas regiones experimentan sequ\u00edas m\u00e1s prolongadas mientras otras enfrentan inundaciones m\u00e1s frecuentes. Los cient\u00edicos colombianos han identificado que las comunidades rurales e ind\u00edgenas son especialmente vulnerables, ya que dependen directamente de los recursos naturales para su subsistencia. El Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC) ha se\u00f1alado que Am\u00e9rica Latina y el Caribe son una de las regiones m\u00e1s susceptibles a estos efectos. En respuesta, Colombia ha implementado pol\u00edticas como la Estrategia Nacional de Cambio Clim\u00e1tico y ha participado activamente en negociaciones internacionales. Sin embargo, los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos. La investigaci\u00f3n cient\u00edfica contin\u00faa siendo fundamental para comprender la magnitud del problema y disenar estrategias de adaptaci\u00f3n efectivas que protejan tanto a las poblaciones humanas como a la biodiversidad \u00fanica del pa\u00eds.`,
        question: '\u00bfQu\u00e9 inferencia v\u00e1lida se puede hacer a partir de la informaci\u00f3n sobre los ecosistemas de p\u00e1ramo?',
        options: ['La p\u00e9rdida de h\u00e1bitat afecta a especies end\u00e9micas de Colombia', 'Los p\u00e1ramos no tienen relaci\u00f3n con el cambio clim\u00e1tico', 'El oso de anteojos se adapta f\u00e1cilmente', 'Los frailejones se encuentran en todos los continentes'],
        correct: 0,
        explanation: { correct: 'Si los p\u00e1ramos sufren contracci\u00f3n y son \u00fanicos, especies end\u00e9micas pierden su h\u00e1bitat.', wrongs: ['El texto establece la relaci\u00f3n p\u00e1ramos-cambio.', 'El texto implica vulnerabilidad.', 'El texto dice que los p\u00e1ramos son \u00fanicos.'] }
    },
    {
        id: 'BL01Q4', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'facil',
        bankId: 'BL01', bankQuestion: 4,
        context: `El cambio clim\u00e1tico constituye una de las amenazas m\u00e1s significativas para los ecosistemas colombianos. Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos frente al aumento de las temperaturas globales. Seg\u00fan el IDEAM, las temperaturas medias en el pa\u00eds han aumentado aproximadamente 0,4\u00b0C en las \u00faltimas d\u00e9cadas, una tendencia que se acelera progresivamente. Este fen\u00f3meno tiene consecuencias directas sobre los glaciares de monta\u00f1a, que han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX. Los ecosistemas de p\u00e1ramo, \u00fanicos en el mundo y hogar de especies como el oso de anteojos y la frailej\u00f3n, sufren una contracci\u00f3n notable de su \u00e1rea de distribuci\u00f3n. Adem\u00e1s, el patr\u00f3n de precipitaciones se ha alterado significativamente: algunas regiones experimentan sequ\u00edas m\u00e1s prolongadas mientras otras enfrentan inundaciones m\u00e1s frecuentes. Los cient\u00edicos colombianos han identificado que las comunidades rurales e ind\u00edgenas son especialmente vulnerables, ya que dependen directamente de los recursos naturales para su subsistencia. El Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC) ha se\u00f1alado que Am\u00e9rica Latina y el Caribe son una de las regiones m\u00e1s susceptibles a estos efectos. En respuesta, Colombia ha implementado pol\u00edticas como la Estrategia Nacional de Cambio Clim\u00e1tico y ha participado activamente en negociaciones internacionales. Sin embargo, los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos. La investigaci\u00f3n cient\u00edfica contin\u00faa siendo fundamental para comprender la magnitud del problema y disenar estrategias de adaptaci\u00f3n efectivas que protejan tanto a las poblaciones humanas como a la biodiversidad \u00fanica del pa\u00eds.`,
        question: '\u00bfQu\u00e9 organismo internacional es mencionado como referencia sobre el cambio clim\u00e1tico?',
        options: ['La ONU y su Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC)', 'La Organizaci\u00f3n Mundial de la Salud (OMS)', 'El Banco Mundial', 'La Organizaci\u00f3n de Estados Americanos (OEA)'],
        correct: 0,
        explanation: { correct: 'El texto menciona expl\u00edcitamente al Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC).', wrongs: ['La OMS no es mencionada.', 'El Banco Mundial no aparece.', 'La OEA no es mencionada.'] }
    },
    {
        id: 'BL01Q5', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'dificil',
        bankId: 'BL01', bankQuestion: 5,
        context: `El cambio clim\u00e1tico constituye una de las amenazas m\u00e1s significativas para los ecosistemas colombianos. Colombia, por su ubicaci\u00f3n ecuatorial y su enorme biodiversidad, enfrenta desaf\u00edos \u00fanicos frente al aumento de las temperaturas globales. Seg\u00fan el IDEAM, las temperaturas medias en el pa\u00eds han aumentado aproximadamente 0,4\u00b0C en las \u00faltimas d\u00e9cadas, una tendencia que se acelera progresivamente. Este fen\u00f3meno tiene consecuencias directas sobre los glaciares de monta\u00f1a, que han perdido m\u00e1s del 50% de su superficie desde mediados del siglo XX. Los ecosistemas de p\u00e1ramo, \u00fanicos en el mundo y hogar de especies como el oso de anteojos y la frailej\u00f3n, sufren una contracci\u00f3n notable de su \u00e1rea de distribuci\u00f3n. Adem\u00e1s, el patr\u00f3n de precipitaciones se ha alterado significativamente: algunas regiones experimentan sequ\u00edas m\u00e1s prolongadas mientras otras enfrentan inundaciones m\u00e1s frecuentes. Los cient\u00edicos colombianos han identificado que las comunidades rurales e ind\u00edgenas son especialmente vulnerables, ya que dependen directamente de los recursos naturales para su subsistencia. El Panel Intergubernamental sobre Cambio Clim\u00e1tico (IPCC) ha se\u00f1alado que Am\u00e9rica Latina y el Caribe son una de las regiones m\u00e1s susceptibles a estos efectos. En respuesta, Colombia ha implementado pol\u00edticas como la Estrategia Nacional de Cambio Clim\u00e1tico y ha participado activamente en negociaciones internacionales. Sin embargo, los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos. La investigaci\u00f3n cient\u00edfica contin\u00faa siendo fundamental para comprender la magnitud del problema y disenar estrategias de adaptaci\u00f3n efectivas que protejan tanto a las poblaciones humanas como a la biodiversidad \u00fanica del pa\u00eds.`,
        question: '\u00bfQu\u00e9 cr\u00edtica impl\u00edtica hacen los cient\u00edicos sobre las acciones gubernamentales?',
        options: ['Que las medidas tomadas no son suficientes para prevenir efectos graves', 'Que el gobierno no ha implementado ninguna pol\u00edtica', 'Que los cient\u00edicos no participan en la investigaci\u00f3n', 'Que las comunidades ind\u00edgenas no deben participar'],
        correct: 0,
        explanation: { correct: 'Los cient\u00edicos advierten que las acciones actuales son insuficientes para mitigar los efectos m\u00e1s severos.', wrongs: ['El texto reconoce pol\u00edticas implementadas.', 'El texto no dice que no participen.', 'El texto no sugiere excluir a comunidades.'] }
    },
    {
        id: 'BL02Q1', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'media',
        bankId: 'BL02', bankQuestion: 1,
        context: `La lluvia ca\u00eda sin piedad sobre las calles de Bogot\u00e1, como si el cielo quisiera borrar cada se\u00f1al de la vida que pululaba en ella. Mar\u00eda caminaba apresurada bajo su paraguas viejo, cuyas varillas resist\u00edan el viento con la misma terquedad con que ella resist\u00eda la vida. Desde ni\u00f1a hab\u00eda aprendido que la lluvia no era solo agua: era memoria, era tiempo detenido, era el \u00e9ter de una ciudad que crec\u00eda sin orden ni concierto. Cada gota que golpeaba el pavimento le recordaba las tardes de su infancia en el barrio de Las Brigadas, donde las casas de ladrillo rojo parec\u00edan rezarle al sol con sus muros calientes. Ahora, cuarenta a\u00f1os despu\u00e9s, aquellas casas hab\u00edan desaparecido bajo el peso de torres de vidrio y concreto que se alzaban como fantasmas modernos. Mar\u00eda sent\u00eda que la ciudad la hab\u00eda abandonado, que cada paso que daba era un paso m\u00e1s lejos de s\u00ed misma. En el mercado de Paloquemao, donde su madre sol\u00eda vender flores, ahora funcionaba una estaci\u00f3n de servicio. Las flores se hab\u00edan mudado a otros barrios, como exiliadas de su propio terru\u00f1o. Ella pensaba que las ciudades, como las personas, tienen memoria propia, una memoria que no depende de lo que sus habitantes recuerdan, sino de lo que el concreto decide conservar. Mientras caminaba, su zapato izquierdo pis\u00f3 un charco profundo, y el agua fr\u00eda le subi\u00f3 por la pierna como un escalofr\u00edo de realidad. Entonces comprendi\u00f3 que no era solo la ciudad la que hab\u00eda cambiado: ella tambi\u00e9n era otra persona, construida capa sobre capa sobre las ruinas de quien hab\u00eda sido. La lluvia segu\u00eda cayendo, indiferente a su epifan\u00eda, y Mar\u00eda continu\u00f3 su camino, ahora con la certeza de que nunca volver\u00eda a encontrar el Bogot\u00e1 de su infancia, pero tambi\u00e9n con la esperanza de que quiz\u00e1s, alg\u00fan d\u00eda, la ciudad pudiera encontrarla a ella.`,
        question: '\u00bfCu\u00e1l es el tema central del fragmento?',
        options: ['La relaci\u00f3n entre la memoria personal y la transformaci\u00f3n urbana', 'La dificultad de vivir en una ciudad con lluvia constante', 'El conflicto entre tradici\u00f3n y modernidad', 'La nostalgia por la infancia perdida en un barrio pobre'],
        correct: 0,
        explanation: { correct: 'El texto articula la memoria de Mar\u00eda con los cambios de la ciudad.', wrongs: ['La lluvia es un elemento simb\u00f3lico, no el tema central.', 'El tema es m\u00e1s amplio y personal.', 'El barrio no es descrito como pobre.'] }
    },
    {
        id: 'BL02Q2', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'dificil',
        bankId: 'BL02', bankQuestion: 2,
        context: `La lluvia ca\u00eda sin piedad sobre las calles de Bogot\u00e1, como si el cielo quisiera borrar cada se\u00f1al de la vida que pululaba en ella. Mar\u00eda caminaba apresurada bajo su paraguas viejo, cuyas varillas resist\u00edan el viento con la misma terquedad con que ella resist\u00eda la vida. Desde ni\u00f1a hab\u00eda aprendido que la lluvia no era solo agua: era memoria, era tiempo detenido, era el \u00e9ter de una ciudad que crec\u00eda sin orden ni concierto. Cada gota que golpeaba el pavimento le recordaba las tardes de su infancia en el barrio de Las Brigadas, donde las casas de ladrillo rojo parec\u00edan rezarle al sol con sus muros calientes. Ahora, cuarenta a\u00f1os despu\u00e9s, aquellas casas hab\u00edan desaparecido bajo el peso de torres de vidrio y concreto que se alzaban como fantasmas modernos. Mar\u00eda sent\u00eda que la ciudad la hab\u00eda abandonado, que cada paso que daba era un paso m\u00e1s lejos de s\u00ed misma. En el mercado de Paloquemao, donde su madre sol\u00eda vender flores, ahora funcionaba una estaci\u00f3n de servicio. Las flores se hab\u00edan mudado a otros barrios, como exiliadas de su propio terru\u00f1o. Ella pensaba que las ciudades, como las personas, tienen memoria propia, una memoria que no depende de lo que sus habitantes recuerdan, sino de lo que el concreto decide conservar. Mientras caminaba, su zapato izquierdo pis\u00f3 un charco profundo, y el agua fr\u00eda le subi\u00f3 por la pierna como un escalofr\u00edo de realidad. Entonces comprendi\u00f3 que no era solo la ciudad la que hab\u00eda cambiado: ella tambi\u00e9n era otra persona, construida capa sobre capa sobre las ruinas de quien hab\u00eda sido. La lluvia segu\u00eda cayendo, indiferente a su epifan\u00eda, y Mar\u00eda continu\u00f3 su camino, ahora con la certeza de que nunca volver\u00eda a encontrar el Bogot\u00e1 de su infancia, pero tambi\u00e9n con la esperanza de que quiz\u00e1s, alg\u00fan d\u00eda, la ciudad pudiera encontrarla a ella.`,
        question: '\u00bfQu\u00e9 recurso literario predomina en "las casas parec\u00edan rezarle al sol"?',
        options: ['Personificaci\u00f3n, al atribuir cualidades humanas a las casas', 'Met\u00e1fora, al comparar las casas con seres vivos', 'Hip\u00e9rbole, al exagerar el calor de los muros', 'S\u00edmbolo, al representar la pobreza del barrio'],
        correct: 0,
        explanation: { correct: 'La personificaci\u00f3n asigna acciones humanas (rezar) a un objeto inanimado (las casas).', wrongs: ['No es una comparaci\u00f3n directa sino una atribuci\u00f3n.', 'No hay exageraci\u00f3n sino imagen sensorial.', 'El s\u00edmbolo no es el recurso predominante.'] }
    },
    {
        id: 'BL02Q3', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'media',
        bankId: 'BL02', bankQuestion: 3,
        context: `La lluvia ca\u00eda sin piedad sobre las calles de Bogot\u00e1, como si el cielo quisiera borrar cada se\u00f1al de la vida que pululaba en ella. Mar\u00eda caminaba apresurada bajo su paraguas viejo, cuyas varillas resist\u00edan el viento con la misma terquedad con que ella resist\u00eda la vida. Desde ni\u00f1a hab\u00eda aprendido que la lluvia no era solo agua: era memoria, era tiempo detenido, era el \u00e9ter de una ciudad que crec\u00eda sin orden ni concierto. Cada gota que golpeaba el pavimento le recordaba las tardes de su infancia en el barrio de Las Brigadas, donde las casas de ladrillo rojo parec\u00edan rezarle al sol con sus muros calientes. Ahora, cuarenta a\u00f1os despu\u00e9s, aquellas casas hab\u00edan desaparecido bajo el peso de torres de vidrio y concreto que se alzaban como fantasmas modernos. Mar\u00eda sent\u00eda que la ciudad la hab\u00eda abandonado, que cada paso que daba era un paso m\u00e1s lejos de s\u00ed misma. En el mercado de Paloquemao, donde su madre sol\u00eda vender flores, ahora funcionaba una estaci\u00f3n de servicio. Las flores se hab\u00edan mudado a otros barrios, como exiliadas de su propio terru\u00f1o. Ella pensaba que las ciudades, como las personas, tienen memoria propia, una memoria que no depende de lo que sus habitantes recuerdan, sino de lo que el concreto decide conservar. Mientras caminaba, su zapato izquierdo pis\u00f3 un charco profundo, y el agua fr\u00eda le subi\u00f3 por la pierna como un escalofr\u00edo de realidad. Entonces comprendi\u00f3 que no era solo la ciudad la que hab\u00eda cambiado: ella tambi\u00e9n era otra persona, construida capa sobre capa sobre las ruinas de quien hab\u00eda sido. La lluvia segu\u00eda cayendo, indiferente a su epifan\u00eda, y Mar\u00eda continu\u00f3 su camino, ahora con la certeza de que nunca volver\u00eda a encontrar el Bogot\u00e1 de su infancia, pero tambi\u00e9n con la esperanza de que quiz\u00e1s, alg\u00fan d\u00eda, la ciudad pudiera encontrarla a ella.`,
        question: '\u00bfQu\u00e9 funci\u00f3n cumple el episodio del charco en el desarrollo del personaje?',
        options: ['Provoca un momento de autoconocimiento y transformaci\u00f3n interna', 'Muestra la negligencia de las autoridades', 'Representa el peligro de caminar en lluvia', 'Simboliza la pobreza extrema del personaje'],
        correct: 0,
        explanation: { correct: 'El charco funciona como detonante de una epifan\u00eda: Mar\u00eda comprende que ella tambi\u00e9n ha cambiado.', wrongs: ['El texto no critica la infraestructura.', 'No hay alusi\u00f3n a peligro.', 'La pobreza no es el tema que el charco representa.'] }
    },
    {
        id: 'BL02Q4', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'facil',
        bankId: 'BL02', bankQuestion: 4,
        context: `La lluvia ca\u00eda sin piedad sobre las calles de Bogot\u00e1, como si el cielo quisiera borrar cada se\u00f1al de la vida que pululaba en ella. Mar\u00eda caminaba apresurada bajo su paraguas viejo, cuyas varillas resist\u00edan el viento con la misma terquedad con que ella resist\u00eda la vida. Desde ni\u00f1a hab\u00eda aprendido que la lluvia no era solo agua: era memoria, era tiempo detenido, era el \u00e9ter de una ciudad que crec\u00eda sin orden ni concierto. Cada gota que golpeaba el pavimento le recordaba las tardes de su infancia en el barrio de Las Brigadas, donde las casas de ladrillo rojo parec\u00edan rezarle al sol con sus muros calientes. Ahora, cuarenta a\u00f1os despu\u00e9s, aquellas casas hab\u00edan desaparecido bajo el peso de torres de vidrio y concreto que se alzaban como fantasmas modernos. Mar\u00eda sent\u00eda que la ciudad la hab\u00eda abandonado, que cada paso que daba era un paso m\u00e1s lejos de s\u00ed misma. En el mercado de Paloquemao, donde su madre sol\u00eda vender flores, ahora funcionaba una estaci\u00f3n de servicio. Las flores se hab\u00edan mudado a otros barrios, como exiliadas de su propio terru\u00f1o. Ella pensaba que las ciudades, como las personas, tienen memoria propia, una memoria que no depende de lo que sus habitantes recuerdan, sino de lo que el concreto decide conservar. Mientras caminaba, su zapato izquierdo pis\u00f3 un charco profundo, y el agua fr\u00eda le subi\u00f3 por la pierna como un escalofr\u00edo de realidad. Entonces comprendi\u00f3 que no era solo la ciudad la que hab\u00eda cambiado: ella tambi\u00e9n era otra persona, construida capa sobre capa sobre las ruinas de quien hab\u00eda sido. La lluvia segu\u00eda cayendo, indiferente a su epifan\u00eda, y Mar\u00eda continu\u00f3 su camino, ahora con la certeza de que nunca volver\u00eda a encontrar el Bogot\u00e1 de su infancia, pero tambi\u00e9n con la esperanza de que quiz\u00e1s, alg\u00fan d\u00eda, la ciudad pudiera encontrarla a ella.`,
        question: '\u00bfQu\u00e9 relaci\u00f3n establece el texto entre la lluvia y la memoria?',
        options: ['La lluvia funciona como detonante de recuerdos y reflexiones', 'La lluvia impide que Mar\u00eda recuerde su pasado', 'La lluvia es solo un elemento decorativo', 'La lluvia representa el olvido y la amnesia colectiva'],
        correct: 0,
        explanation: { correct: 'El texto dice que cada gota le recordaba las tardes de su infancia y que la lluvia era memoria.', wrongs: ['La lluvia activa los recuerdos, no los impide.', 'La lluvia tiene un papel simb\u00f3lico fundamental.', 'La lluvia representa memoria, no olvido.'] }
    },
    {
        id: 'BL02Q5', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'dificil',
        bankId: 'BL02', bankQuestion: 5,
        context: `La lluvia ca\u00eda sin piedad sobre las calles de Bogot\u00e1, como si el cielo quisiera borrar cada se\u00f1al de la vida que pululaba en ella. Mar\u00eda caminaba apresurada bajo su paraguas viejo, cuyas varillas resist\u00edan el viento con la misma terquedad con que ella resist\u00eda la vida. Desde ni\u00f1a hab\u00eda aprendido que la lluvia no era solo agua: era memoria, era tiempo detenido, era el \u00e9ter de una ciudad que crec\u00eda sin orden ni concierto. Cada gota que golpeaba el pavimento le recordaba las tardes de su infancia en el barrio de Las Brigadas, donde las casas de ladrillo rojo parec\u00edan rezarle al sol con sus muros calientes. Ahora, cuarenta a\u00f1os despu\u00e9s, aquellas casas hab\u00edan desaparecido bajo el peso de torres de vidrio y concreto que se alzaban como fantasmas modernos. Mar\u00eda sent\u00eda que la ciudad la hab\u00eda abandonado, que cada paso que daba era un paso m\u00e1s lejos de s\u00ed misma. En el mercado de Paloquemao, donde su madre sol\u00eda vender flores, ahora funcionaba una estaci\u00f3n de servicio. Las flores se hab\u00edan mudado a otros barrios, como exiliadas de su propio terru\u00f1o. Ella pensaba que las ciudades, como las personas, tienen memoria propia, una memoria que no depende de lo que sus habitantes recuerdan, sino de lo que el concreto decide conservar. Mientras caminaba, su zapato izquierdo pis\u00f3 un charco profundo, y el agua fr\u00eda le subi\u00f3 por la pierna como un escalofr\u00edo de realidad. Entonces comprendi\u00f3 que no era solo la ciudad la que hab\u00eda cambiado: ella tambi\u00e9n era otra persona, construida capa sobre capa sobre las ruinas de quien hab\u00eda sido. La lluvia segu\u00eda cayendo, indiferente a su epifan\u00eda, y Mar\u00eda continu\u00f3 su camino, ahora con la certeza de que nunca volver\u00eda a encontrar el Bogot\u00e1 de su infancia, pero tambi\u00e9n con la esperanza de que quiz\u00e1s, alg\u00fan d\u00eda, la ciudad pudiera encontrarla a ella.`,
        question: '\u00bfCu\u00e1l es la interpretaci\u00f3n m\u00e1s profunda de "la ciudad pudiera encontrarla a ella"?',
        options: ['Mar\u00eda espera reconectar con su identidad a trav\u00e9s de la ciudad transformada', 'Mar\u00eda quiere que la ciudad le devuelva sus pertenencias', 'Mar\u00eda desea que la ciudad la reconozca como importante', 'Mar\u00eda espera que la ciudad deje de construir edificios'],
        correct: 0,
        explanation: { correct: 'La frase implica un deseo de reconexi\u00f3n identitaria.', wrongs: ['No hay alusi\u00f3n a pertenencias materiales.', 'No busca reconocimiento social.', 'No hay cr\u00edtica a la modernizaci\u00f3n.'] }
    },
    {
        id: 'BL03Q1', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'media',
        bankId: 'BL03', bankQuestion: 1,
        context: `El proceso de independencia de Colombia fue un fen\u00f3meno complejo que no puede reducirse a un \u00fanico evento, sino que se desarroll\u00f3 a lo largo de varias d\u00e9cadas marcadas por tensiones pol\u00edticas, sociales y econ\u00f3micas. Las reformas borb\u00f3nicas del siglo XVIII, que centralizaron el poder y limitaron los privilegios de las \u00e9lites criollas, sembraron las primeras semillas del descontento. Cuando en 1808 Napole\u00f3n Bonaparte invadi\u00f3 Espa\u00f1a y oblig\u00f3 a Fernando VII a abdicar, las colonias americanas aprovecharon la crisis para iniciar procesos auton\u00f3micos. El 20 de julio de 1810, en Bogot\u00e1, se produjo el Grito de Independencia, un movimiento impulsado principalmente por criollos que buscaban reemplazar el dominio espa\u00f1ol por un gobierno propio. Sin embargo, este primer intento fracas\u00f3 por las profundas divisiones internas: los federalistas y centralistas discrepancias impidieron la creaci\u00f3n de un Estado estable. El Per\u00edodo de la Patria Boba (1810-1816) estuvo marcado por guerras civiles entre regiones que no lograron ponerse de acuerdo sobre la forma de gobierno. La Reconquista espa\u00f1ola de 1815, liderada por Pablo Morillo, trajo una represi\u00f3n brutal que, parad\u00f3jicamente, unific\u00f3 a los independentistas. La Campa\u00f1a Libertadora de 1819, liderada por Sim\u00f3n Bol\u00edvar, culmin\u00f3 con la Batalla del Pantano de Vargas y la creaci\u00f3n de la Gran Colombia. Aunque la independencia se logr\u00f3 militarmente, los retos de construir una naci\u00f3n unida persistieron durante d\u00e9cadas, como lo demuestran las posteriores disoluciones de la Gran Colombia y las numerosas guerras civiles del siglo XIX.`,
        question: '\u00bfCu\u00e1l fue el factor que m\u00e1s contribuy\u00f3 a la unificaci\u00f3n de los independentistas?',
        options: ['La represi\u00f3n espa\u00f1ola durante la Reconquista de 1815', 'La llegada de Sim\u00f3n Bol\u00edvar', 'El apoyo econ\u00f3mico de otras colonias', 'La ca\u00edda del imperio napole\u00f3nico'],
        correct: 0,
        explanation: { correct: 'La Reconquista espa\u00f1ola trajo represi\u00f3n brutal que parad\u00f3jicamente unific\u00f3 a los independentistas.', wrongs: ['Bol\u00edvar lider\u00f3 despu\u00e9s de la unificaci\u00f3n.', 'No menciona apoyo econ\u00f3mico externo.', 'Fue factor inicial, no de unificaci\u00f3n.'] }
    },
    {
        id: 'BL03Q2', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'dificil',
        bankId: 'BL03', bankQuestion: 2,
        context: `El proceso de independencia de Colombia fue un fen\u00f3meno complejo que no puede reducirse a un \u00fanico evento, sino que se desarroll\u00f3 a lo largo de varias d\u00e9cadas marcadas por tensiones pol\u00edticas, sociales y econ\u00f3micas. Las reformas borb\u00f3nicas del siglo XVIII, que centralizaron el poder y limitaron los privilegios de las \u00e9lites criollas, sembraron las primeras semillas del descontento. Cuando en 1808 Napole\u00f3n Bonaparte invadi\u00f3 Espa\u00f1a y oblig\u00f3 a Fernando VII a abdicar, las colonias americanas aprovecharon la crisis para iniciar procesos auton\u00f3micos. El 20 de julio de 1810, en Bogot\u00e1, se produjo el Grito de Independencia, un movimiento impulsado principalmente por criollos que buscaban reemplazar el dominio espa\u00f1ol por un gobierno propio. Sin embargo, este primer intento fracas\u00f3 por las profundas divisiones internas: los federalistas y centralistas discrepancias impidieron la creaci\u00f3n de un Estado estable. El Per\u00edodo de la Patria Boba (1810-1816) estuvo marcado por guerras civiles entre regiones que no lograron ponerse de acuerdo sobre la forma de gobierno. La Reconquista espa\u00f1ola de 1815, liderada por Pablo Morillo, trajo una represi\u00f3n brutal que, parad\u00f3jicamente, unific\u00f3 a los independentistas. La Campa\u00f1a Libertadora de 1819, liderada por Sim\u00f3n Bol\u00edvar, culmin\u00f3 con la Batalla del Pantano de Vargas y la creaci\u00f3n de la Gran Colombia. Aunque la independencia se logr\u00f3 militarmente, los retos de construir una naci\u00f3n unida persistieron durante d\u00e9cadas, como lo demuestran las posteriores disoluciones de la Gran Colombia y las numerosas guerras civiles del siglo XIX.`,
        question: '\u00bfCu\u00e1l fue la contradicci\u00f3n hist\u00f3rica m\u00e1s relevante del proceso independentista?',
        options: ['Que la opresi\u00f3n espa\u00f1ola termin\u00f3 unificando a quienes estaban divididos', 'Que los criollos quer\u00edan un sistema similar al espa\u00f1ol', 'Que la independencia se logr\u00f3 sin violencia', 'Que las \u00e9lites ind\u00edgenas lideraron el movimiento'],
        correct: 0,
        explanation: { correct: 'El texto usa "parad\u00f3jicamente" para describir c\u00f3mo la reconquista uni\u00e9ndolos.', wrongs: ['El texto no dice que quer\u00edan un sistema similar.', 'Fue un proceso violento.', 'No menciona liderazgo ind\u00edgena.'] }
    },
    {
        id: 'BL03Q3', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'media',
        bankId: 'BL03', bankQuestion: 3,
        context: `El proceso de independencia de Colombia fue un fen\u00f3meno complejo que no puede reducirse a un \u00fanico evento, sino que se desarroll\u00f3 a lo largo de varias d\u00e9cadas marcadas por tensiones pol\u00edticas, sociales y econ\u00f3micas. Las reformas borb\u00f3nicas del siglo XVIII, que centralizaron el poder y limitaron los privilegios de las \u00e9lites criollas, sembraron las primeras semillas del descontento. Cuando en 1808 Napole\u00f3n Bonaparte invadi\u00f3 Espa\u00f1a y oblig\u00f3 a Fernando VII a abdicar, las colonias americanas aprovecharon la crisis para iniciar procesos auton\u00f3micos. El 20 de julio de 1810, en Bogot\u00e1, se produjo el Grito de Independencia, un movimiento impulsado principalmente por criollos que buscaban reemplazar el dominio espa\u00f1ol por un gobierno propio. Sin embargo, este primer intento fracas\u00f3 por las profundas divisiones internas: los federalistas y centralistas discrepancias impidieron la creaci\u00f3n de un Estado estable. El Per\u00edodo de la Patria Boba (1810-1816) estuvo marcado por guerras civiles entre regiones que no lograron ponerse de acuerdo sobre la forma de gobierno. La Reconquista espa\u00f1ola de 1815, liderada por Pablo Morillo, trajo una represi\u00f3n brutal que, parad\u00f3jicamente, unific\u00f3 a los independentistas. La Campa\u00f1a Libertadora de 1819, liderada por Sim\u00f3n Bol\u00edvar, culmin\u00f3 con la Batalla del Pantano de Vargas y la creaci\u00f3n de la Gran Colombia. Aunque la independencia se logr\u00f3 militarmente, los retos de construir una naci\u00f3n unida persistieron durante d\u00e9cadas, como lo demuestran las posteriores disoluciones de la Gran Colombia y las numerosas guerras civiles del siglo XIX.`,
        question: '\u00bfPor qu\u00e9 razones los historiadores consideran a la Patria Boba como un fracaso?',
        options: ['Por las guerras civiles entre federalistas y centralistas', 'Por la falta de l\u00edderes militares', 'Por el escaso apoyo popular', 'Por la intervenci\u00f3n de potencias europeas'],
        correct: 0,
        explanation: { correct: 'Las discrepancias entre federalistas y centralistas impidieron la creaci\u00f3n de un Estado estable.', wrongs: ['No menciona falta de l\u00edderes.', 'El apoyo popular no es factor negativo.', 'No describe intervenci\u00f3n de potencias.'] }
    },
    {
        id: 'BL03Q4', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'facil',
        bankId: 'BL03', bankQuestion: 4,
        context: `El proceso de independencia de Colombia fue un fen\u00f3meno complejo que no puede reducirse a un \u00fanico evento, sino que se desarroll\u00f3 a lo largo de varias d\u00e9cadas marcadas por tensiones pol\u00edticas, sociales y econ\u00f3micas. Las reformas borb\u00f3nicas del siglo XVIII, que centralizaron el poder y limitaron los privilegios de las \u00e9lites criollas, sembraron las primeras semillas del descontento. Cuando en 1808 Napole\u00f3n Bonaparte invadi\u00f3 Espa\u00f1a y oblig\u00f3 a Fernando VII a abdicar, las colonias americanas aprovecharon la crisis para iniciar procesos auton\u00f3micos. El 20 de julio de 1810, en Bogot\u00e1, se produjo el Grito de Independencia, un movimiento impulsado principalmente por criollos que buscaban reemplazar el dominio espa\u00f1ol por un gobierno propio. Sin embargo, este primer intento fracas\u00f3 por las profundas divisiones internas: los federalistas y centralistas discrepancias impidieron la creaci\u00f3n de un Estado estable. El Per\u00edodo de la Patria Boba (1810-1816) estuvo marcado por guerras civiles entre regiones que no lograron ponerse de acuerdo sobre la forma de gobierno. La Reconquista espa\u00f1ola de 1815, liderada por Pablo Morillo, trajo una represi\u00f3n brutal que, parad\u00f3jicamente, unific\u00f3 a los independentistas. La Campa\u00f1a Libertadora de 1819, liderada por Sim\u00f3n Bol\u00edvar, culmin\u00f3 con la Batalla del Pantano de Vargas y la creaci\u00f3n de la Gran Colombia. Aunque la independencia se logr\u00f3 militarmente, los retos de construir una naci\u00f3n unida persistieron durante d\u00e9cadas, como lo demuestran las posteriores disoluciones de la Gran Colombia y las numerosas guerras civiles del siglo XIX.`,
        question: '\u00bfCu\u00e1l fue el detonante inmediato del movimiento independentista en 1810?',
        options: ['La invasi\u00f3n napole\u00f3nica de Espa\u00f1a y la crisis pol\u00edtica', 'La llegada de Sim\u00f3n Bol\u00edvar', 'La firma del Tratado de Tordesillas', 'La revoluci\u00f3n francesa de 1789'],
        correct: 0,
        explanation: { correct: 'Cuando Napole\u00f3n invadi\u00f3 Espa\u00f1a en 1808, las colonias aprovecharon la crisis.', wrongs: ['Bol\u00edvar lleg\u00f3 despu\u00e9s.', 'El Tratado es de 1494.', 'La revoluci\u00f3n es contexto, no detonante directo.'] }
    },
    {
        id: 'BL03Q5', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'dificil',
        bankId: 'BL03', bankQuestion: 5,
        context: `El proceso de independencia de Colombia fue un fen\u00f3meno complejo que no puede reducirse a un \u00fanico evento, sino que se desarroll\u00f3 a lo largo de varias d\u00e9cadas marcadas por tensiones pol\u00edticas, sociales y econ\u00f3micas. Las reformas borb\u00f3nicas del siglo XVIII, que centralizaron el poder y limitaron los privilegios de las \u00e9lites criollas, sembraron las primeras semillas del descontento. Cuando en 1808 Napole\u00f3n Bonaparte invadi\u00f3 Espa\u00f1a y oblig\u00f3 a Fernando VII a abdicar, las colonias americanas aprovecharon la crisis para iniciar procesos auton\u00f3micos. El 20 de julio de 1810, en Bogot\u00e1, se produjo el Grito de Independencia, un movimiento impulsado principalmente por criollos que buscaban reemplazar el dominio espa\u00f1ol por un gobierno propio. Sin embargo, este primer intento fracas\u00f3 por las profundas divisiones internas: los federalistas y centralistas discrepancias impidieron la creaci\u00f3n de un Estado estable. El Per\u00edodo de la Patria Boba (1810-1816) estuvo marcado por guerras civiles entre regiones que no lograron ponerse de acuerdo sobre la forma de gobierno. La Reconquista espa\u00f1ola de 1815, liderada por Pablo Morillo, trajo una represi\u00f3n brutal que, parad\u00f3jicamente, unific\u00f3 a los independentistas. La Campa\u00f1a Libertadora de 1819, liderada por Sim\u00f3n Bol\u00edvar, culmin\u00f3 con la Batalla del Pantano de Vargas y la creaci\u00f3n de la Gran Colombia. Aunque la independencia se logr\u00f3 militarmente, los retos de construir una naci\u00f3n unida persistieron durante d\u00e9cadas, como lo demuestran las posteriores disoluciones de la Gran Colombia y las numerosas guerras civiles del siglo XIX.`,
        question: '\u00bfQu\u00e9 cr\u00edtica hist\u00f3rica impl\u00edcita hace el texto sobre el legado de la independencia?',
        options: ['Que la independencia pol\u00edtica no garantiz\u00f3 cohesi\u00f3n social ni estabilidad', 'Que la independencia fue un error', 'Que los l\u00edderes no ten\u00edan visi\u00f3n de futuro', 'Que Espa\u00f1a debi\u00f3 seguir gobernando'],
        correct: 0,
        explanation: { correct: 'La independencia se logr\u00f3 militarmente pero la cohesi\u00f3n no se logr\u00f3.', wrongs: ['No dice que fuera un error.', 'No critica la visi\u00f3n de los l\u00edderes.', 'No defiende el dominio espa\u00f1ol.'] }
    },
    {
        id: 'BL04Q1', area: 'matematicas', areaName: 'Matem\u00e1ticas', difficulty: 'media',
        bankId: 'BL04', bankQuestion: 1,
        context: `La Alcald\u00eda de Medell\u00edn est\u00e1 dise\u00f1ando un nuevo parque urbano en el barrio Santo Domingo, una zona de ladera con terreno irregular. El parque tendr\u00e1 tres \u00e1reas principales: una zona verde con jardines, una \u00e1rea recreativa con juegos infantiles y una plazoleta con sillas y mesas. El terreno total disponible tiene forma rectangular de 120 metros de largo por 80 metros de ancho. Los ingenieros han determinado que la zona verde ocupar\u00e1 el 45% del \u00e1rea total, la \u00e1rea recreativa el 30% y la plazoleta el 15%, dejando el 10% restante para v\u00edas peatonales y jardines de transici\u00f3n. El presupuesto asignado para la construcci\u00f3n es de .000.000 pesos, de los cuales el 35% se destinar\u00e1 a la zona verde, el 40% a la \u00e1rea recreativa y el 25% restante entre la plazoleta y las v\u00edas peatonales. Adem\u00e1s, el dise\u00f1o debe cumplir con la normativa municipal que exige que cada \u00e1rea tenga acceso directo a al menos un camino peatonal y que la zona verde no pueda estar a m\u00e1s de 50 metros de la \u00e1rea recreativa. Los planos muestran que el terreno tiene una pendiente del 15% en su zona norte, lo que obliga a considerar costos adicionales de estabilizaci\u00f3n del suelo en un 12% sobre el presupuesto base de esa \u00e1rea espec\u00edfica.`,
        question: '\u00bfCu\u00e1l es el \u00e1rea exacta en m\u00b2 que ocupar\u00e1 la zona verde?',
        options: ['4.320 m\u00b2', '3.600 m\u00b2', '5.400 m\u00b2', '2.880 m\u00b2'],
        correct: 0,
        explanation: { correct: 'El \u00e1rea total es 120 x 80 = 9.600 m\u00b2. La zona verde es el 45%: 9.600 x 0,45 = 4.320 m\u00b2.', wrongs: ['3.600 es el 37,5%.', '5.400 es el 56,25%.', '2.880 es el 30%.'] }
    },
    {
        id: 'BL04Q2', area: 'matematicas', areaName: 'Matem\u00e1ticas', difficulty: 'dificil',
        bankId: 'BL04', bankQuestion: 2,
        context: `La Alcald\u00eda de Medell\u00edn est\u00e1 dise\u00f1ando un nuevo parque urbano en el barrio Santo Domingo, una zona de ladera con terreno irregular. El parque tendr\u00e1 tres \u00e1reas principales: una zona verde con jardines, una \u00e1rea recreativa con juegos infantiles y una plazoleta con sillas y mesas. El terreno total disponible tiene forma rectangular de 120 metros de largo por 80 metros de ancho. Los ingenieros han determinado que la zona verde ocupar\u00e1 el 45% del \u00e1rea total, la \u00e1rea recreativa el 30% y la plazoleta el 15%, dejando el 10% restante para v\u00edas peatonales y jardines de transici\u00f3n. El presupuesto asignado para la construcci\u00f3n es de .000.000 pesos, de los cuales el 35% se destinar\u00e1 a la zona verde, el 40% a la \u00e1rea recreativa y el 25% restante entre la plazoleta y las v\u00edas peatonales. Adem\u00e1s, el dise\u00f1o debe cumplir con la normativa municipal que exige que cada \u00e1rea tenga acceso directo a al menos un camino peatonal y que la zona verde no pueda estar a m\u00e1s de 50 metros de la \u00e1rea recreativa. Los planos muestran que el terreno tiene una pendiente del 15% en su zona norte, lo que obliga a considerar costos adicionales de estabilizaci\u00f3n del suelo en un 12% sobre el presupuesto base de esa \u00e1rea espec\u00edfica.`,
        question: '\u00bfCu\u00e1l es el presupuesto para la \u00e1rea recreativa incluyendo recargo si est\u00e1 en zona norte?',
        options: ['$340.000.000 m\u00e1s 12% de recargo', '$306.000.000 m\u00e1s 12% de recargo', '$374.000.000 sin recargo', '$212.500.000 m\u00e1s 12% de recargo'],
        correct: 0,
        explanation: { correct: 'El 40% de $850.000.000 es $340.000.000. Con 12% de recargo en zona norte.', wrongs: ['$306.000.000 es el 36%.', '$374.000.000 no corresponde al 40%.', '$212.500.000 es el 25%.'] }
    },
    {
        id: 'BL04Q3', area: 'matematicas', areaName: 'Matem\u00e1ticas', difficulty: 'media',
        bankId: 'BL04', bankQuestion: 3,
        context: `La Alcald\u00eda de Medell\u00edn est\u00e1 dise\u00f1ando un nuevo parque urbano en el barrio Santo Domingo, una zona de ladera con terreno irregular. El parque tendr\u00e1 tres \u00e1reas principales: una zona verde con jardines, una \u00e1rea recreativa con juegos infantiles y una plazoleta con sillas y mesas. El terreno total disponible tiene forma rectangular de 120 metros de largo por 80 metros de ancho. Los ingenieros han determinado que la zona verde ocupar\u00e1 el 45% del \u00e1rea total, la \u00e1rea recreativa el 30% y la plazoleta el 15%, dejando el 10% restante para v\u00edas peatonales y jardines de transici\u00f3n. El presupuesto asignado para la construcci\u00f3n es de .000.000 pesos, de los cuales el 35% se destinar\u00e1 a la zona verde, el 40% a la \u00e1rea recreativa y el 25% restante entre la plazoleta y las v\u00edas peatonales. Adem\u00e1s, el dise\u00f1o debe cumplir con la normativa municipal que exige que cada \u00e1rea tenga acceso directo a al menos un camino peatonal y que la zona verde no pueda estar a m\u00e1s de 50 metros de la \u00e1rea recreativa. Los planos muestran que el terreno tiene una pendiente del 15% en su zona norte, lo que obliga a considerar costos adicionales de estabilizaci\u00f3n del suelo en un 12% sobre el presupuesto base de esa \u00e1rea espec\u00edfica.`,
        question: '\u00bfCu\u00e1l es el \u00e1rea total destinada a la plazoleta y las v\u00edas peatonales combinadas?',
        options: ['2.400 m\u00b2', '1.440 m\u00b2', '2.880 m\u00b2', '3.840 m\u00b2'],
        correct: 0,
        explanation: { correct: 'La plazoleta es 15% y las v\u00edas 10%, total 25%. 9.600 x 0,25 = 2.400 m\u00b2.', wrongs: ['1.440 es solo el 15%.', '2.880 es solo el 30%.', '3.840 es el 40%.'] }
    },
    {
        id: 'BL04Q4', area: 'matematicas', areaName: 'Matem\u00e1ticas', difficulty: 'facil',
        bankId: 'BL04', bankQuestion: 4,
        context: `La Alcald\u00eda de Medell\u00edn est\u00e1 dise\u00f1ando un nuevo parque urbano en el barrio Santo Domingo, una zona de ladera con terreno irregular. El parque tendr\u00e1 tres \u00e1reas principales: una zona verde con jardines, una \u00e1rea recreativa con juegos infantiles y una plazoleta con sillas y mesas. El terreno total disponible tiene forma rectangular de 120 metros de largo por 80 metros de ancho. Los ingenieros han determinado que la zona verde ocupar\u00e1 el 45% del \u00e1rea total, la \u00e1rea recreativa el 30% y la plazoleta el 15%, dejando el 10% restante para v\u00edas peatonales y jardines de transici\u00f3n. El presupuesto asignado para la construcci\u00f3n es de .000.000 pesos, de los cuales el 35% se destinar\u00e1 a la zona verde, el 40% a la \u00e1rea recreativa y el 25% restante entre la plazoleta y las v\u00edas peatonales. Adem\u00e1s, el dise\u00f1o debe cumplir con la normativa municipal que exige que cada \u00e1rea tenga acceso directo a al menos un camino peatonal y que la zona verde no pueda estar a m\u00e1s de 50 metros de la \u00e1rea recreativa. Los planos muestran que el terreno tiene una pendiente del 15% en su zona norte, lo que obliga a considerar costos adicionales de estabilizaci\u00f3n del suelo en un 12% sobre el presupuesto base de esa \u00e1rea espec\u00edfica.`,
        question: '\u00bfCu\u00e1l es el \u00e1rea total del terreno disponible?',
        options: ['9.600 m\u00b2', '8.400 m\u00b2', '10.800 m\u00b2', '7.200 m\u00b2'],
        correct: 0,
        explanation: { correct: 'El \u00e1rea de un rect\u00e1ngulo es largo por ancho: 120 x 80 = 9.600 m\u00b2.', wrongs: ['8.400 no corresponde.', '10.800 excede el \u00e1rea real.', '7.200 es menor.'] }
    },
    {
        id: 'BL04Q5', area: 'matematicas', areaName: 'Matem\u00e1ticas', difficulty: 'dificil',
        bankId: 'BL04', bankQuestion: 5,
        context: `La Alcald\u00eda de Medell\u00edn est\u00e1 dise\u00f1ando un nuevo parque urbano en el barrio Santo Domingo, una zona de ladera con terreno irregular. El parque tendr\u00e1 tres \u00e1reas principales: una zona verde con jardines, una \u00e1rea recreativa con juegos infantiles y una plazoleta con sillas y mesas. El terreno total disponible tiene forma rectangular de 120 metros de largo por 80 metros de ancho. Los ingenieros han determinado que la zona verde ocupar\u00e1 el 45% del \u00e1rea total, la \u00e1rea recreativa el 30% y la plazoleta el 15%, dejando el 10% restante para v\u00edas peatonales y jardines de transici\u00f3n. El presupuesto asignado para la construcci\u00f3n es de .000.000 pesos, de los cuales el 35% se destinar\u00e1 a la zona verde, el 40% a la \u00e1rea recreativa y el 25% restante entre la plazoleta y las v\u00edas peatonales. Adem\u00e1s, el dise\u00f1o debe cumplir con la normativa municipal que exige que cada \u00e1rea tenga acceso directo a al menos un camino peatonal y que la zona verde no pueda estar a m\u00e1s de 50 metros de la \u00e1rea recreativa. Los planos muestran que el terreno tiene una pendiente del 15% en su zona norte, lo que obliga a considerar costos adicionales de estabilizaci\u00f3n del suelo en un 12% sobre el presupuesto base de esa \u00e1rea espec\u00edfica.`,
        question: '\u00bfCu\u00e1l es el costo destinado a la zona verde si toda est\u00e1 en zona norte con pendiente?',
        options: ['$297.500.000 m\u00e1s 12% = $333.200.000', '$340.000.000 m\u00e1s 12% = $380.800.000', '$374.000.000 m\u00e1s 12% = $418.880.000', '$850.000.000 m\u00e1s 12% = $952.000.000'],
        correct: 0,
        explanation: { correct: 'El 35% de $850.000.000 es $297.500.000. Con 12%: $333.200.000.', wrongs: ['$340.000.000 es el 40%.', '$374.000.000 no corresponde al 35%.', '$850.000.000 es el total.'] }
    },
    {
        id: 'BL05Q1', area: 'ingles', areaName: 'Ingl\u00e9s', difficulty: 'media',
        bankId: 'BL05', bankQuestion: 1,
        context: `Artificial Intelligence (AI) has rapidly transformed from a futuristic concept into an integral part of our daily lives. From virtual assistants like Siri and Alexa to sophisticated recommendation algorithms on platforms like Netflix and Spotify, AI systems are increasingly shaping how we interact with technology and with each other. In healthcare, AI-powered diagnostic tools can analyze medical images with accuracy rivaling that of experienced radiologists, potentially saving countless lives through early detection of diseases. However, the rapid advancement of AI also raises significant ethical concerns. Job displacement is perhaps the most immediate worry: as AI systems become capable of performing tasks previously done by humans, millions of workers in manufacturing, transportation, and even white-collar professions face the prospect of unemployment. Furthermore, algorithmic bias has emerged as a critical issue, with studies showing that AI systems can perpetuate and even amplify existing social inequalities. For instance, facial recognition technology has demonstrated lower accuracy rates for people of color, and hiring algorithms have been found to discriminate against women. Privacy concerns also loom large, as AI systems often require vast amounts of personal data to function effectively. Despite these challenges, proponents argue that AI has the potential to solve some of humanity's most pressing problems, from climate change to disease prevention. The key, they suggest, lies in developing AI responsibly, with robust regulatory frameworks that balance innovation with the protection of fundamental rights.`,
        question: 'According to the text, what is one of the most immediate concerns about AI advancement?',
        options: ['Job displacement across various sectors', 'The high cost of implementing AI systems', 'The difficulty of training AI models', 'The slow pace of AI development'],
        correct: 0,
        explanation: { correct: 'The text states that job displacement is perhaps the most immediate worry.', wrongs: ['Implementation costs are not mentioned.', 'Training difficulty is not discussed.', 'AI is described as rapidly advancing.'] }
    },
    {
        id: 'BL05Q2', area: 'ingles', areaName: 'Ingl\u00e9s', difficulty: 'dificil',
        bankId: 'BL05', bankQuestion: 2,
        context: `Artificial Intelligence (AI) has rapidly transformed from a futuristic concept into an integral part of our daily lives. From virtual assistants like Siri and Alexa to sophisticated recommendation algorithms on platforms like Netflix and Spotify, AI systems are increasingly shaping how we interact with technology and with each other. In healthcare, AI-powered diagnostic tools can analyze medical images with accuracy rivaling that of experienced radiologists, potentially saving countless lives through early detection of diseases. However, the rapid advancement of AI also raises significant ethical concerns. Job displacement is perhaps the most immediate worry: as AI systems become capable of performing tasks previously done by humans, millions of workers in manufacturing, transportation, and even white-collar professions face the prospect of unemployment. Furthermore, algorithmic bias has emerged as a critical issue, with studies showing that AI systems can perpetuate and even amplify existing social inequalities. For instance, facial recognition technology has demonstrated lower accuracy rates for people of color, and hiring algorithms have been found to discriminate against women. Privacy concerns also loom large, as AI systems often require vast amounts of personal data to function effectively. Despite these challenges, proponents argue that AI has the potential to solve some of humanity's most pressing problems, from climate change to disease prevention. The key, they suggest, lies in developing AI responsibly, with robust regulatory frameworks that balance innovation with the protection of fundamental rights.`,
        question: 'Which example does the text provide to illustrate algorithmic bias?',
        options: ['Facial recognition systems showing lower accuracy for people of color', 'Virtual assistants failing to understand accents', 'Recommendation algorithms producing repetitive content', 'AI systems consuming excessive energy'],
        correct: 0,
        explanation: { correct: 'Facial recognition technology has demonstrated lower accuracy rates for people of color.', wrongs: ['Accent recognition is not mentioned.', 'Repetitive content is not discussed.', 'Energy consumption is not mentioned.'] }
    },
    {
        id: 'BL05Q3', area: 'ingles', areaName: 'Ingl\u00e9s', difficulty: 'media',
        bankId: 'BL05', bankQuestion: 3,
        context: `Artificial Intelligence (AI) has rapidly transformed from a futuristic concept into an integral part of our daily lives. From virtual assistants like Siri and Alexa to sophisticated recommendation algorithms on platforms like Netflix and Spotify, AI systems are increasingly shaping how we interact with technology and with each other. In healthcare, AI-powered diagnostic tools can analyze medical images with accuracy rivaling that of experienced radiologists, potentially saving countless lives through early detection of diseases. However, the rapid advancement of AI also raises significant ethical concerns. Job displacement is perhaps the most immediate worry: as AI systems become capable of performing tasks previously done by humans, millions of workers in manufacturing, transportation, and even white-collar professions face the prospect of unemployment. Furthermore, algorithmic bias has emerged as a critical issue, with studies showing that AI systems can perpetuate and even amplify existing social inequalities. For instance, facial recognition technology has demonstrated lower accuracy rates for people of color, and hiring algorithms have been found to discriminate against women. Privacy concerns also loom large, as AI systems often require vast amounts of personal data to function effectively. Despite these challenges, proponents argue that AI has the potential to solve some of humanity's most pressing problems, from climate change to disease prevention. The key, they suggest, lies in developing AI responsibly, with robust regulatory frameworks that balance innovation with the protection of fundamental rights.`,
        question: 'What positive application of AI in healthcare does the text mention?',
        options: ['Diagnostic tools that analyze medical images for early disease detection', 'Robotic surgery systems', 'AI-powered drug manufacturing', 'Virtual therapy sessions'],
        correct: 0,
        explanation: { correct: 'AI-powered diagnostic tools can analyze medical images with accuracy rivaling experienced radiologists.', wrongs: ['Robotic surgery is not mentioned.', 'AI drug manufacturing is not discussed.', 'Virtual therapy is not mentioned.'] }
    },
    {
        id: 'BL05Q4', area: 'ingles', areaName: 'Ingl\u00e9s', difficulty: 'facil',
        bankId: 'BL05', bankQuestion: 4,
        context: `Artificial Intelligence (AI) has rapidly transformed from a futuristic concept into an integral part of our daily lives. From virtual assistants like Siri and Alexa to sophisticated recommendation algorithms on platforms like Netflix and Spotify, AI systems are increasingly shaping how we interact with technology and with each other. In healthcare, AI-powered diagnostic tools can analyze medical images with accuracy rivaling that of experienced radiologists, potentially saving countless lives through early detection of diseases. However, the rapid advancement of AI also raises significant ethical concerns. Job displacement is perhaps the most immediate worry: as AI systems become capable of performing tasks previously done by humans, millions of workers in manufacturing, transportation, and even white-collar professions face the prospect of unemployment. Furthermore, algorithmic bias has emerged as a critical issue, with studies showing that AI systems can perpetuate and even amplify existing social inequalities. For instance, facial recognition technology has demonstrated lower accuracy rates for people of color, and hiring algorithms have been found to discriminate against women. Privacy concerns also loom large, as AI systems often require vast amounts of personal data to function effectively. Despite these challenges, proponents argue that AI has the potential to solve some of humanity's most pressing problems, from climate change to disease prevention. The key, they suggest, lies in developing AI responsibly, with robust regulatory frameworks that balance innovation with the protection of fundamental rights.`,
        question: 'Which is NOT mentioned as an example of AI in everyday life?',
        options: ['Self-driving cars navigating urban streets', 'Virtual assistants like Siri and Alexa', 'Recommendation algorithms on Netflix', 'Recommendation algorithms on Spotify'],
        correct: 0,
        explanation: { correct: 'Self-driving cars are not mentioned in the text.', wrongs: ['Siri and Alexa are mentioned.', 'Netflix algorithms are mentioned.', 'Spotify algorithms are mentioned.'] }
    },
    {
        id: 'BL05Q5', area: 'ingles', areaName: 'Ingl\u00e9s', difficulty: 'dificil',
        bankId: 'BL05', bankQuestion: 5,
        context: `Artificial Intelligence (AI) has rapidly transformed from a futuristic concept into an integral part of our daily lives. From virtual assistants like Siri and Alexa to sophisticated recommendation algorithms on platforms like Netflix and Spotify, AI systems are increasingly shaping how we interact with technology and with each other. In healthcare, AI-powered diagnostic tools can analyze medical images with accuracy rivaling that of experienced radiologists, potentially saving countless lives through early detection of diseases. However, the rapid advancement of AI also raises significant ethical concerns. Job displacement is perhaps the most immediate worry: as AI systems become capable of performing tasks previously done by humans, millions of workers in manufacturing, transportation, and even white-collar professions face the prospect of unemployment. Furthermore, algorithmic bias has emerged as a critical issue, with studies showing that AI systems can perpetuate and even amplify existing social inequalities. For instance, facial recognition technology has demonstrated lower accuracy rates for people of color, and hiring algorithms have been found to discriminate against women. Privacy concerns also loom large, as AI systems often require vast amounts of personal data to function effectively. Despite these challenges, proponents argue that AI has the potential to solve some of humanity's most pressing problems, from climate change to disease prevention. The key, they suggest, lies in developing AI responsibly, with robust regulatory frameworks that balance innovation with the protection of fundamental rights.`,
        question: 'What position do proponents of AI take regarding its challenges?',
        options: ['AI can solve major problems if developed responsibly with proper regulations', 'The challenges are minor and need no regulation', 'AI development should be halted', 'Only government agencies should develop AI'],
        correct: 0,
        explanation: { correct: 'Proponents suggest developing AI responsibly with robust regulatory frameworks.', wrongs: ['Challenges are not described as minor.', 'No one advocates halting development.', 'Government-only development is not discussed.'] }
    },
    {
        id: 'BL06Q1', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'media',
        bankId: 'BL06', bankQuestion: 1,
        context: `Colombia es reconocida como uno de los pa\u00edses m\u00e1s megadiversos del mundo, albergando aproximadamente el 10% de las especies de la biodiversidad global. Esta riqueza biol\u00f3gica se debe a su posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central, su variada topograf\u00eda que incluye tres cordilleras andinas, y su acceso a dos oc\u00e9anos. El pa\u00eds alberga m\u00e1s de 55.000 especies de plantas, 1.800 especies de aves, 526 especies de mam\u00edferos y m\u00e1s de 4.000 especies de mariposas, superando a pa\u00edses como Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea. Los ecosistemas colombianos incluyen selvas tropicales h\u00famedas, p\u00e1ramos de alta monta\u00f1a, manglares, ecosistemas de niebla y bosques de ribera, cada uno con comunidades \u00e9nicas \u00fanicas. Sin embargo, esta biodiversidad enfrenta amenazas cr\u00edticas: la deforestaci\u00f3n, que entre 2001 y 2020 afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas; la contaminaci\u00f3n de cuerpos de agua por actividad minera; y el cambio clim\u00e1tico que altera los patrones de precipitaci\u00f3n y temperatura. Los cient\u00edicos han identificado que al menos 2.000 especies de flora y fauna se encuentran en categor\u00edas de amenaza, desde vulnerables hasta cr\u00edticamente en peligro de extinci\u00f3n. Las estrategias de conservaci\u00f3n incluyen la creaci\u00f3n de \u00e1reas protegidas que actualmente cubren el 16% del territorio continental, programas de restauraci\u00f3n ecol\u00f3gica y esfuerzos de bioprospecci\u00f3n que buscan valorar econ\u00f3micamente la biodiversidad sin destruirla.`,
        question: '\u00bfQu\u00e9 factor geogr\u00e1fico es causa principal de la megadiversidad colombiana?',
        options: ['La posici\u00f3n en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central', 'La cercan\u00eda al ecuador', 'La presencia de grandes r\u00edos navegables', 'La extensi\u00f3n de costas en el Atl\u00e1ntico'],
        correct: 0,
        explanation: { correct: 'La posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n es la causa principal.', wrongs: ['La cercan\u00eda al ecuador no es el factor principal.', 'Los r\u00edos no son mencionados.', 'Las costas no son identificadas como factor principal.'] }
    },
    {
        id: 'BL06Q2', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'dificil',
        bankId: 'BL06', bankQuestion: 2,
        context: `Colombia es reconocida como uno de los pa\u00edses m\u00e1s megadiversos del mundo, albergando aproximadamente el 10% de las especies de la biodiversidad global. Esta riqueza biol\u00f3gica se debe a su posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central, su variada topograf\u00eda que incluye tres cordilleras andinas, y su acceso a dos oc\u00e9anos. El pa\u00eds alberga m\u00e1s de 55.000 especies de plantas, 1.800 especies de aves, 526 especies de mam\u00edferos y m\u00e1s de 4.000 especies de mariposas, superando a pa\u00edses como Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea. Los ecosistemas colombianos incluyen selvas tropicales h\u00famedas, p\u00e1ramos de alta monta\u00f1a, manglares, ecosistemas de niebla y bosques de ribera, cada uno con comunidades \u00e9nicas \u00fanicas. Sin embargo, esta biodiversidad enfrenta amenazas cr\u00edticas: la deforestaci\u00f3n, que entre 2001 y 2020 afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas; la contaminaci\u00f3n de cuerpos de agua por actividad minera; y el cambio clim\u00e1tico que altera los patrones de precipitaci\u00f3n y temperatura. Los cient\u00edicos han identificado que al menos 2.000 especies de flora y fauna se encuentran en categor\u00edas de amenaza, desde vulnerables hasta cr\u00edticamente en peligro de extinci\u00f3n. Las estrategias de conservaci\u00f3n incluyen la creaci\u00f3n de \u00e1reas protegidas que actualmente cubren el 16% del territorio continental, programas de restauraci\u00f3n ecol\u00f3gica y esfuerzos de bioprospecci\u00f3n que buscan valorar econ\u00f3micamente la biodiversidad sin destruirla.`,
        question: '\u00bfQu\u00e9 relaci\u00f3n establece entre diversidad por unidad de \u00e1rea y Brasil?',
        options: ['Colombia tiene m\u00e1s especies por km\u00b2 que Brasil', 'Brasil tiene m\u00e1s diversidad total pero menos por \u00e1rea', 'Ambos tienen la misma diversidad por unidad', 'El texto no establece comparaci\u00f3n'],
        correct: 0,
        explanation: { correct: 'Colombia supera a Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea.', wrongs: ['No dice que Brasil tenga m\u00e1s total.', 'Establece diferencia, no igualdad.', 'S\u00ed hay comparaci\u00f3n directa.'] }
    },
    {
        id: 'BL06Q3', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'media',
        bankId: 'BL06', bankQuestion: 3,
        context: `Colombia es reconocida como uno de los pa\u00edses m\u00e1s megadiversos del mundo, albergando aproximadamente el 10% de las especies de la biodiversidad global. Esta riqueza biol\u00f3gica se debe a su posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central, su variada topograf\u00eda que incluye tres cordilleras andinas, y su acceso a dos oc\u00e9anos. El pa\u00eds alberga m\u00e1s de 55.000 especies de plantas, 1.800 especies de aves, 526 especies de mam\u00edferos y m\u00e1s de 4.000 especies de mariposas, superando a pa\u00edses como Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea. Los ecosistemas colombianos incluyen selvas tropicales h\u00famedas, p\u00e1ramos de alta monta\u00f1a, manglares, ecosistemas de niebla y bosques de ribera, cada uno con comunidades \u00e9nicas \u00fanicas. Sin embargo, esta biodiversidad enfrenta amenazas cr\u00edticas: la deforestaci\u00f3n, que entre 2001 y 2020 afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas; la contaminaci\u00f3n de cuerpos de agua por actividad minera; y el cambio clim\u00e1tico que altera los patrones de precipitaci\u00f3n y temperatura. Los cient\u00edicos han identificado que al menos 2.000 especies de flora y fauna se encuentran en categor\u00edas de amenaza, desde vulnerables hasta cr\u00edticamente en peligro de extinci\u00f3n. Las estrategias de conservaci\u00f3n incluyen la creaci\u00f3n de \u00e1reas protegidas que actualmente cubren el 16% del territorio continental, programas de restauraci\u00f3n ecol\u00f3gica y esfuerzos de bioprospecci\u00f3n que buscan valorar econ\u00f3micamente la biodiversidad sin destruirla.`,
        question: '\u00bfCu\u00e1l es la amenaza que ha afectado la mayor superficie territorial?',
        options: ['La deforestaci\u00f3n, con m\u00e1s de 3 millones de hect\u00e1reas', 'La contaminaci\u00f3n minera', 'El cambio clim\u00e1tico en monta\u00f1a', 'La urbanizaci\u00f3n de zonas rurales'],
        correct: 0,
        explanation: { correct: 'La deforestaci\u00f3n afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas.', wrongs: ['La contaminaci\u00f3n no es cuantificada en hect\u00e1reas.', 'El cambio clim\u00e1tico altera patrones.', 'La urbanizaci\u00f3n no es mencionada.'] }
    },
    {
        id: 'BL06Q4', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'facil',
        bankId: 'BL06', bankQuestion: 4,
        context: `Colombia es reconocida como uno de los pa\u00edses m\u00e1s megadiversos del mundo, albergando aproximadamente el 10% de las especies de la biodiversidad global. Esta riqueza biol\u00f3gica se debe a su posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central, su variada topograf\u00eda que incluye tres cordilleras andinas, y su acceso a dos oc\u00e9anos. El pa\u00eds alberga m\u00e1s de 55.000 especies de plantas, 1.800 especies de aves, 526 especies de mam\u00edferos y m\u00e1s de 4.000 especies de mariposas, superando a pa\u00edses como Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea. Los ecosistemas colombianos incluyen selvas tropicales h\u00famedas, p\u00e1ramos de alta monta\u00f1a, manglares, ecosistemas de niebla y bosques de ribera, cada uno con comunidades \u00e9nicas \u00fanicas. Sin embargo, esta biodiversidad enfrenta amenazas cr\u00edticas: la deforestaci\u00f3n, que entre 2001 y 2020 afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas; la contaminaci\u00f3n de cuerpos de agua por actividad minera; y el cambio clim\u00e1tico que altera los patrones de precipitaci\u00f3n y temperatura. Los cient\u00edicos han identificado que al menos 2.000 especies de flora y fauna se encuentran en categor\u00edas de amenaza, desde vulnerables hasta cr\u00edticamente en peligro de extinci\u00f3n. Las estrategias de conservaci\u00f3n incluyen la creaci\u00f3n de \u00e1reas protegidas que actualmente cubren el 16% del territorio continental, programas de restauraci\u00f3n ecol\u00f3gica y esfuerzos de bioprospecci\u00f3n que buscan valorar econ\u00f3micamente la biodiversidad sin destruirla.`,
        question: '\u00bfCu\u00e1ntas especies de aves alberga Colombia?',
        options: ['1.800 especies', '55.000 especies', '526 especies', '4.000 especies'],
        correct: 0,
        explanation: { correct: 'Colombia alberga 1.800 especies de aves.', wrongs: ['55.000 es el n\u00famero de plantas.', '526 es el de mam\u00edferos.', '4.000 es el de mariposas.'] }
    },
    {
        id: 'BL06Q5', area: 'ciencias', areaName: 'Ciencias Naturales', difficulty: 'dificil',
        bankId: 'BL06', bankQuestion: 5,
        context: `Colombia es reconocida como uno de los pa\u00edses m\u00e1s megadiversos del mundo, albergando aproximadamente el 10% de las especies de la biodiversidad global. Esta riqueza biol\u00f3gica se debe a su posici\u00f3n geogr\u00e1fica privilegiada en la intersecci\u00f3n de Sudam\u00e9rica y Am\u00e9rica Central, su variada topograf\u00eda que incluye tres cordilleras andinas, y su acceso a dos oc\u00e9anos. El pa\u00eds alberga m\u00e1s de 55.000 especies de plantas, 1.800 especies de aves, 526 especies de mam\u00edferos y m\u00e1s de 4.000 especies de mariposas, superando a pa\u00edses como Brasil en t\u00e9rminos de diversidad por unidad de \u00e1rea. Los ecosistemas colombianos incluyen selvas tropicales h\u00famedas, p\u00e1ramos de alta monta\u00f1a, manglares, ecosistemas de niebla y bosques de ribera, cada uno con comunidades \u00e9nicas \u00fanicas. Sin embargo, esta biodiversidad enfrenta amenazas cr\u00edticas: la deforestaci\u00f3n, que entre 2001 y 2020 afect\u00f3 m\u00e1s de 3 millones de hect\u00e1reas; la contaminaci\u00f3n de cuerpos de agua por actividad minera; y el cambio clim\u00e1tico que altera los patrones de precipitaci\u00f3n y temperatura. Los cient\u00edicos han identificado que al menos 2.000 especies de flora y fauna se encuentran en categor\u00edas de amenaza, desde vulnerables hasta cr\u00edticamente en peligro de extinci\u00f3n. Las estrategias de conservaci\u00f3n incluyen la creaci\u00f3n de \u00e1reas protegidas que actualmente cubren el 16% del territorio continental, programas de restauraci\u00f3n ecol\u00f3gica y esfuerzos de bioprospecci\u00f3n que buscan valorar econ\u00f3micamente la biodiversidad sin destruirla.`,
        question: '\u00bfQu\u00e9 implica el concepto de "bioprospecci\u00f3n" como estrategia de conservaci\u00f3n?',
        options: ['Buscar valor econ\u00f3mico en la biodiversidad sin destruirla', 'Extraer minerales sosteniblemente', 'Replantar \u00e1rboles para obtener madera', 'Capturar especies para venderlas internacionalmente'],
        correct: 0,
        explanation: { correct: 'La bioprospecci\u00f3n busca valorar econ\u00f3micamente la biodiversidad sin destruirla.', wrongs: ['No se refiere a extracci\u00f3n minera.', 'No es reforestaci\u00f3n maderera.', 'Captura contradice conservaci\u00f3n.'] }
    },
    {
        id: 'BL07Q1', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'media',
        bankId: 'BL07', bankQuestion: 1,
        context: `La econom\u00eda colombiana ha experimentado transformaciones significativas en su estructura comercial durante las \u00faltimas d\u00e9cadas. Hist\u00f3ricamente dependiente de la exportaci\u00f3n de productos primarios como el caf\u00e9, el petr\u00f3leo y el carb\u00f3n, Colombia ha buscado diversificar su canasta exportadora para reducir la vulnerabilidad ante las fluctuaciones de precios internacionales. Los Tratados de Libre Comercio (TLC) firmados con Estados Unidos (2012), la Uni\u00f3n Europea (2013) y Corea del Sur (2016) han abierto nuevos mercados para productos colombianos, particularmente en sectores como las flores, los pl\u00e1ticos, los textiles y los productos agroindustriales. Sin embargo, la diversificaci\u00f3n ha sido desigual: mientras las exportaciones no tradicionales crecieron un 8% anual entre 2010 y 2019, las commodities siguieron representando m\u00e1s del 60% del total exportado. La crisis del petr\u00f3leo en 2014-2016 expuso esta dependencia, generando una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente. Actualmente, sectores como el turismo, los servicios tecnol\u00f3gicos y la agroindustria muestran potencial de crecimiento exportador. El gobierno ha implementado pol\u00edticas de apoyo a mipymes exportadoras, facilitaci\u00f3n aduanera y promoci\u00f3n comercial a trav\u00e9s de ProColombia. No obstante, persisten desaf\u00edos como la informalidad empresarial, la infraestructura deficiente y la percepci\u00f3n de riesgo que afectan la competitividad colombiana en mercados globales.`,
        question: '\u00bfCu\u00e1l fue la consecuencia principal de la crisis del petr\u00f3leo de 2014-2016?',
        options: ['Una contracci\u00f3n del PIB y d\u00e9ficit en la cuenta corriente', 'Un aumento del empleo minero', 'Una diversificaci\u00f3n exitosa', 'Un crecimiento del turismo'],
        correct: 0,
        explanation: { correct: 'La crisis gener\u00f3 una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente.', wrongs: ['Caus\u00f3 p\u00e9rdida de empleo.', 'Expuso falta de diversificaci\u00f3n.', 'El turismo es potencial futuro.'] }
    },
    {
        id: 'BL07Q2', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'dificil',
        bankId: 'BL07', bankQuestion: 2,
        context: `La econom\u00eda colombiana ha experimentado transformaciones significativas en su estructura comercial durante las \u00faltimas d\u00e9cadas. Hist\u00f3ricamente dependiente de la exportaci\u00f3n de productos primarios como el caf\u00e9, el petr\u00f3leo y el carb\u00f3n, Colombia ha buscado diversificar su canasta exportadora para reducir la vulnerabilidad ante las fluctuaciones de precios internacionales. Los Tratados de Libre Comercio (TLC) firmados con Estados Unidos (2012), la Uni\u00f3n Europea (2013) y Corea del Sur (2016) han abierto nuevos mercados para productos colombianos, particularmente en sectores como las flores, los pl\u00e1ticos, los textiles y los productos agroindustriales. Sin embargo, la diversificaci\u00f3n ha sido desigual: mientras las exportaciones no tradicionales crecieron un 8% anual entre 2010 y 2019, las commodities siguieron representando m\u00e1s del 60% del total exportado. La crisis del petr\u00f3leo en 2014-2016 expuso esta dependencia, generando una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente. Actualmente, sectores como el turismo, los servicios tecnol\u00f3gicos y la agroindustria muestran potencial de crecimiento exportador. El gobierno ha implementado pol\u00edticas de apoyo a mipymes exportadoras, facilitaci\u00f3n aduanera y promoci\u00f3n comercial a trav\u00e9s de ProColombia. No obstante, persisten desaf\u00edos como la informalidad empresarial, la infraestructura deficiente y la percepci\u00f3n de riesgo que afectan la competitividad colombiana en mercados globales.`,
        question: '\u00bfQu\u00e9 paradoja econ\u00f3mica describe sobre la diversificaci\u00f3n exportadora?',
        options: ['Que las exportaciones no tradicionales crecieron pero las commodities siguen dominando', 'Que los TLC generaron m\u00e1s importaciones', 'Que el agro creci\u00f3 pero el caf\u00e9 decreci\u00f3', 'Que la apertura s\u00f3lo benefici\u00f3 grandes empresas'],
        correct: 0,
        explanation: { correct: 'Las exportaciones no tradicionales crecieron 8% anual, pero las commodities siguen al 60%.', wrongs: ['No dice que TLC generaron m\u00e1s importaciones.', 'El caf\u00e9 no es mencionado como decreciente.', 'No analiza efecto por tama\u00f1o empresarial.'] }
    },
    {
        id: 'BL07Q3', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'media',
        bankId: 'BL07', bankQuestion: 3,
        context: `La econom\u00eda colombiana ha experimentado transformaciones significativas en su estructura comercial durante las \u00faltimas d\u00e9cadas. Hist\u00f3ricamente dependiente de la exportaci\u00f3n de productos primarios como el caf\u00e9, el petr\u00f3leo y el carb\u00f3n, Colombia ha buscado diversificar su canasta exportadora para reducir la vulnerabilidad ante las fluctuaciones de precios internacionales. Los Tratados de Libre Comercio (TLC) firmados con Estados Unidos (2012), la Uni\u00f3n Europea (2013) y Corea del Sur (2016) han abierto nuevos mercados para productos colombianos, particularmente en sectores como las flores, los pl\u00e1ticos, los textiles y los productos agroindustriales. Sin embargo, la diversificaci\u00f3n ha sido desigual: mientras las exportaciones no tradicionales crecieron un 8% anual entre 2010 y 2019, las commodities siguieron representando m\u00e1s del 60% del total exportado. La crisis del petr\u00f3leo en 2014-2016 expuso esta dependencia, generando una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente. Actualmente, sectores como el turismo, los servicios tecnol\u00f3gicos y la agroindustria muestran potencial de crecimiento exportador. El gobierno ha implementado pol\u00edticas de apoyo a mipymes exportadoras, facilitaci\u00f3n aduanera y promoci\u00f3n comercial a trav\u00e9s de ProColombia. No obstante, persisten desaf\u00edos como la informalidad empresarial, la infraestructura deficiente y la percepci\u00f3n de riesgo que afectan la competitividad colombiana en mercados globales.`,
        question: '\u00bfCu\u00e1les son los tres TLC m\u00e1s relevantes mencionados?',
        options: ['Estados Unidos (2012), Uni\u00f3n Europea (2013) y Corea del Sur (2016)', 'M\u00e9xico (2011), Chile (2009) y Per\u00fa (2012)', 'China (2010), Jap\u00f3n (2014) y Canad\u00e1 (2015)', 'Venezuela (2005), Ecuador (2008) y Brasil (2010)'],
        correct: 0,
        explanation: { correct: 'Estados Unidos (2012), Uni\u00f3n Europea (2013) y Corea del Sur (2016).', wrongs: ['Estos pa\u00edses no son los mencionados.', 'No aparecen en el texto.', 'No son mencionados en TLC.'] }
    },
    {
        id: 'BL07Q4', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'facil',
        bankId: 'BL07', bankQuestion: 4,
        context: `La econom\u00eda colombiana ha experimentado transformaciones significativas en su estructura comercial durante las \u00faltimas d\u00e9cadas. Hist\u00f3ricamente dependiente de la exportaci\u00f3n de productos primarios como el caf\u00e9, el petr\u00f3leo y el carb\u00f3n, Colombia ha buscado diversificar su canasta exportadora para reducir la vulnerabilidad ante las fluctuaciones de precios internacionales. Los Tratados de Libre Comercio (TLC) firmados con Estados Unidos (2012), la Uni\u00f3n Europea (2013) y Corea del Sur (2016) han abierto nuevos mercados para productos colombianos, particularmente en sectores como las flores, los pl\u00e1ticos, los textiles y los productos agroindustriales. Sin embargo, la diversificaci\u00f3n ha sido desigual: mientras las exportaciones no tradicionales crecieron un 8% anual entre 2010 y 2019, las commodities siguieron representando m\u00e1s del 60% del total exportado. La crisis del petr\u00f3leo en 2014-2016 expuso esta dependencia, generando una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente. Actualmente, sectores como el turismo, los servicios tecnol\u00f3gicos y la agroindustria muestran potencial de crecimiento exportador. El gobierno ha implementado pol\u00edticas de apoyo a mipymes exportadoras, facilitaci\u00f3n aduanera y promoci\u00f3n comercial a trav\u00e9s de ProColombia. No obstante, persisten desaf\u00edos como la informalidad empresarial, la infraestructura deficiente y la percepci\u00f3n de riesgo que afectan la competitividad colombiana en mercados globales.`,
        question: '\u00bfCu\u00e1les son los tres productos primarios que dominaron las exportaciones?',
        options: ['Caf\u00e9, petr\u00f3leo y carb\u00f3n', 'Banano, flores y az\u00facar', 'Oro, esmeraldas y plata', 'Cacao, tabaco y algod\u00f3n'],
        correct: 0,
        explanation: { correct: 'Colombia fue dependiente del caf\u00e9, el petr\u00f3leo y el carb\u00f3n.', wrongs: ['No son los mencionados como dominantes.', 'No son los tres principales.', 'No aparecen en el texto.'] }
    },
    {
        id: 'BL07Q5', area: 'sociales', areaName: 'Ciencias Sociales', difficulty: 'dificil',
        bankId: 'BL07', bankQuestion: 5,
        context: `La econom\u00eda colombiana ha experimentado transformaciones significativas en su estructura comercial durante las \u00faltimas d\u00e9cadas. Hist\u00f3ricamente dependiente de la exportaci\u00f3n de productos primarios como el caf\u00e9, el petr\u00f3leo y el carb\u00f3n, Colombia ha buscado diversificar su canasta exportadora para reducir la vulnerabilidad ante las fluctuaciones de precios internacionales. Los Tratados de Libre Comercio (TLC) firmados con Estados Unidos (2012), la Uni\u00f3n Europea (2013) y Corea del Sur (2016) han abierto nuevos mercados para productos colombianos, particularmente en sectores como las flores, los pl\u00e1ticos, los textiles y los productos agroindustriales. Sin embargo, la diversificaci\u00f3n ha sido desigual: mientras las exportaciones no tradicionales crecieron un 8% anual entre 2010 y 2019, las commodities siguieron representando m\u00e1s del 60% del total exportado. La crisis del petr\u00f3leo en 2014-2016 expuso esta dependencia, generando una contracci\u00f3n del PIB y un d\u00e9ficit en la cuenta corriente. Actualmente, sectores como el turismo, los servicios tecnol\u00f3gicos y la agroindustria muestran potencial de crecimiento exportador. El gobierno ha implementado pol\u00edticas de apoyo a mipymes exportadoras, facilitaci\u00f3n aduanera y promoci\u00f3n comercial a trav\u00e9s de ProColombia. No obstante, persisten desaf\u00edos como la informalidad empresarial, la infraestructura deficiente y la percepci\u00f3n de riesgo que afectan la competitividad colombiana en mercados globales.`,
        question: '\u00bfQu\u00e9 desaf\u00edos estructurales identifica como obst\u00e1culos para la competitividad?',
        options: ['Informalidad empresarial, infraestructura deficiente y percepci\u00f3n de riesgo', 'Falta de capital humano y bajo nivel educativo', 'Exceso de regulaci\u00f3n y burocracia', 'Dependencia de la ayuda internacional'],
        correct: 0,
        explanation: { correct: 'Informalidad empresarial, infraestructura deficiente y percepci\u00f3n de riesgo.', wrongs: ['No menciona capital humano.', 'No menciona regulaci\u00f3n/burocracia.', 'No menciona ayuda internacional.'] }
    },
    {
        id: 'BL08Q1', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'media',
        bankId: 'BL08', bankQuestion: 1,
        context: `La narrativa latinoamericana del siglo XX experiment\u00f3 una revoluci\u00f3n est\u00e9tica sin precedentes con el surgimiento del realismo m\u00e1gico, un movimiento literario que fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural de una manera que cuestion\u00f3 los l\u00edmites tradicionales de la ficci\u00f3n. Gabriel Garc\u00eda M\u00e1rquez, considerado el m\u00e1ximo exponente de esta corriente, logr\u00f3 en Cien a\u00f1os de soledad una obra que trascendi\u00f3 las fronteras literarias para convertirse en un fen\u00f3meno cultural global. Su t\u00e9cnica narrativa, que mezcla cronolog\u00edas lineales con saltos temporales yuxtapuestos, crea una percepci\u00f3n del tiempo como algo c\u00edclico y maleable, reflejando la cosmovisi\u00f3n de las comunidades rurales colombianas. La cr\u00edtica literaria ha identificado varios elementos fundamentales en esta obra: el uso de la hiperb\u00f3le como recurso para expresar realidades emocionales, la personificaci\u00f3n de elementos naturales como extensiones de la psicolog\u00eda de los personajes, y la construcci\u00f3n de un universo ficticio (Macondo) que funciona como alegor\u00eda de toda Am\u00e9rica Latina. Sin embargo, algunos cr\u00edticos como Mario Vargas Llosa han cuestionado si el realismo m\u00e1gico no representa una forma de exotizaci\u00f3n de la realidad latinoamericana, reduci\u00e9ndola a elementos folcl\u00f3ricos en lugar de abordar sus complejidades pol\u00edticas y sociales. Otros estudiosos argumentan que precisamente la fus\u00f3n de lo m\u00e1gico y lo real permite una cr\u00edtica m\u00e1s profunda de las estructuras de poder y las din\u00e1micas sociales de la regi\u00f3n.`,
        question: '\u00bfCu\u00e1l es la caracter\u00edstica est\u00e9tica principal del realismo m\u00e1gico?',
        options: ['La fusi\u00f3n de la realidad cotidiana con lo sobrenatural', 'La representaci\u00f3n fiel de la sociedad', 'El uso exclusivo de di\u00d1\u00a1logos', 'La experimentaci\u00f3n con estructuras lineales'],
        correct: 0,
        explanation: { correct: 'El realismo m\u00e1gico fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural.', wrongs: ['La representaci\u00f3n fiel es del realismo tradicional.', 'No usa di\u00d1\u00a1logos exclusivamente.', 'Usa estructuras no lineales.'] }
    },
    {
        id: 'BL08Q2', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'dificil',
        bankId: 'BL08', bankQuestion: 2,
        context: `La narrativa latinoamericana del siglo XX experiment\u00f3 una revoluci\u00f3n est\u00e9tica sin precedentes con el surgimiento del realismo m\u00e1gico, un movimiento literario que fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural de una manera que cuestion\u00f3 los l\u00edmites tradicionales de la ficci\u00f3n. Gabriel Garc\u00eda M\u00e1rquez, considerado el m\u00e1ximo exponente de esta corriente, logr\u00f3 en Cien a\u00f1os de soledad una obra que trascendi\u00f3 las fronteras literarias para convertirse en un fen\u00f3meno cultural global. Su t\u00e9cnica narrativa, que mezcla cronolog\u00edas lineales con saltos temporales yuxtapuestos, crea una percepci\u00f3n del tiempo como algo c\u00edclico y maleable, reflejando la cosmovisi\u00f3n de las comunidades rurales colombianas. La cr\u00edtica literaria ha identificado varios elementos fundamentales en esta obra: el uso de la hiperb\u00f3le como recurso para expresar realidades emocionales, la personificaci\u00f3n de elementos naturales como extensiones de la psicolog\u00eda de los personajes, y la construcci\u00f3n de un universo ficticio (Macondo) que funciona como alegor\u00eda de toda Am\u00e9rica Latina. Sin embargo, algunos cr\u00edticos como Mario Vargas Llosa han cuestionado si el realismo m\u00e1gico no representa una forma de exotizaci\u00f3n de la realidad latinoamericana, reduci\u00e9ndola a elementos folcl\u00f3ricos en lugar de abordar sus complejidades pol\u00edticas y sociales. Otros estudiosos argumentan que precisamente la fus\u00f3n de lo m\u00e1gico y lo real permite una cr\u00edtica m\u00e1s profunda de las estructuras de poder y las din\u00e1micas sociales de la regi\u00f3n.`,
        question: '\u00bfQu\u00e9 cr\u00edtica hace Mario Vargas Llosa al realismo m\u00e1gico?',
        options: ['Que puede representar una exotizaci\u00f3n de la realidad', 'Que no es un movimiento leg\u00edtimo', 'Que carece de calidad literaria', 'Que es demasiado realista para ser ficci\u00f3n'],
        correct: 0,
        explanation: { correct: 'Vargas Llosa cuestiona si representa una forma de exotizaci\u00f3n de la realidad.', wrongs: ['No dice que no sea leg\u00edtimo.', 'No cuestiona la calidad.', 'No habla de exceso de realismo.'] }
    },
    {
        id: 'BL08Q3', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'media',
        bankId: 'BL08', bankQuestion: 3,
        context: `La narrativa latinoamericana del siglo XX experiment\u00f3 una revoluci\u00f3n est\u00e9tica sin precedentes con el surgimiento del realismo m\u00e1gico, un movimiento literario que fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural de una manera que cuestion\u00f3 los l\u00edmites tradicionales de la ficci\u00f3n. Gabriel Garc\u00eda M\u00e1rquez, considerado el m\u00e1ximo exponente de esta corriente, logr\u00f3 en Cien a\u00f1os de soledad una obra que trascendi\u00f3 las fronteras literarias para convertirse en un fen\u00f3meno cultural global. Su t\u00e9cnica narrativa, que mezcla cronolog\u00edas lineales con saltos temporales yuxtapuestos, crea una percepci\u00f3n del tiempo como algo c\u00edclico y maleable, reflejando la cosmovisi\u00f3n de las comunidades rurales colombianas. La cr\u00edtica literaria ha identificado varios elementos fundamentales en esta obra: el uso de la hiperb\u00f3le como recurso para expresar realidades emocionales, la personificaci\u00f3n de elementos naturales como extensiones de la psicolog\u00eda de los personajes, y la construcci\u00f3n de un universo ficticio (Macondo) que funciona como alegor\u00eda de toda Am\u00e9rica Latina. Sin embargo, algunos cr\u00edticos como Mario Vargas Llosa han cuestionado si el realismo m\u00e1gico no representa una forma de exotizaci\u00f3n de la realidad latinoamericana, reduci\u00e9ndola a elementos folcl\u00f3ricos en lugar de abordar sus complejidades pol\u00edticas y sociales. Otros estudiosos argumentan que precisamente la fus\u00f3n de lo m\u00e1gico y lo real permite una cr\u00edtica m\u00e1s profunda de las estructuras de poder y las din\u00e1micas sociales de la regi\u00f3n.`,
        question: '\u00bfQu\u00e9 funci\u00f3n cumple Macondo en Cien a\u00f1os de soledad?',
        options: ['Funciona como alegor\u00eda de toda Am\u00e9rica Latina', 'Es un lugar real descrito fielmente', 'Representa solo la infancia del autor', 'Simboliza el progreso tecnol\u00f3gico'],
        correct: 0,
        explanation: { correct: 'Macondo funciona como alegor\u00eda de toda Am\u00e9rica Latina.', wrongs: ['No dice que sea un lugar real.', 'No lo vincula con la infancia.', 'No lo asocia con progreso.'] }
    },
    {
        id: 'BL08Q4', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'facil',
        bankId: 'BL08', bankQuestion: 4,
        context: `La narrativa latinoamericana del siglo XX experiment\u00f3 una revoluci\u00f3n est\u00e9tica sin precedentes con el surgimiento del realismo m\u00e1gico, un movimiento literario que fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural de una manera que cuestion\u00f3 los l\u00edmites tradicionales de la ficci\u00f3n. Gabriel Garc\u00eda M\u00e1rquez, considerado el m\u00e1ximo exponente de esta corriente, logr\u00f3 en Cien a\u00f1os de soledad una obra que trascendi\u00f3 las fronteras literarias para convertirse en un fen\u00f3meno cultural global. Su t\u00e9cnica narrativa, que mezcla cronolog\u00edas lineales con saltos temporales yuxtapuestos, crea una percepci\u00f3n del tiempo como algo c\u00edclico y maleable, reflejando la cosmovisi\u00f3n de las comunidades rurales colombianas. La cr\u00edtica literaria ha identificado varios elementos fundamentales en esta obra: el uso de la hiperb\u00f3le como recurso para expresar realidades emocionales, la personificaci\u00f3n de elementos naturales como extensiones de la psicolog\u00eda de los personajes, y la construcci\u00f3n de un universo ficticio (Macondo) que funciona como alegor\u00eda de toda Am\u00e9rica Latina. Sin embargo, algunos cr\u00edticos como Mario Vargas Llosa han cuestionado si el realismo m\u00e1gico no representa una forma de exotizaci\u00f3n de la realidad latinoamericana, reduci\u00e9ndola a elementos folcl\u00f3ricos en lugar de abordar sus complejidades pol\u00edticas y sociales. Otros estudiosos argumentan que precisamente la fus\u00f3n de lo m\u00e1gico y lo real permite una cr\u00edtica m\u00e1s profunda de las estructuras de poder y las din\u00e1micas sociales de la regi\u00f3n.`,
        question: '\u00bfQui\u00e9n es considerado el m\u00e1ximo exponente del realismo m\u00e1gico?',
        options: ['Gabriel Garc\u00eda M\u00e1rquez', 'Mario Vargas Llosa', 'Julio Cort\u00e1zar', 'Pablo Neruda'],
        correct: 0,
        explanation: { correct: 'Gabriel Garc\u00eda M\u00e1rquez es considerado el m\u00e1ximo exponente.', wrongs: ['Vargas Llosa es cr\u00edtico, no exponente.', 'Cort\u00e1zar no es mencionado.', 'Neruda no es mencionado.'] }
    },
    {
        id: 'BL08Q5', area: 'lectura', areaName: 'Lectura Cr\u00edtica', difficulty: 'dificil',
        bankId: 'BL08', bankQuestion: 5,
        context: `La narrativa latinoamericana del siglo XX experiment\u00f3 una revoluci\u00f3n est\u00e9tica sin precedentes con el surgimiento del realismo m\u00e1gico, un movimiento literario que fusion\u00f3 elementos de la realidad cotidiana con lo sobrenatural de una manera que cuestion\u00f3 los l\u00edmites tradicionales de la ficci\u00f3n. Gabriel Garc\u00eda M\u00e1rquez, considerado el m\u00e1ximo exponente de esta corriente, logr\u00f3 en Cien a\u00f1os de soledad una obra que trascendi\u00f3 las fronteras literarias para convertirse en un fen\u00f3meno cultural global. Su t\u00e9cnica narrativa, que mezcla cronolog\u00edas lineales con saltos temporales yuxtapuestos, crea una percepci\u00f3n del tiempo como algo c\u00edclico y maleable, reflejando la cosmovisi\u00f3n de las comunidades rurales colombianas. La cr\u00edtica literaria ha identificado varios elementos fundamentales en esta obra: el uso de la hiperb\u00f3le como recurso para expresar realidades emocionales, la personificaci\u00f3n de elementos naturales como extensiones de la psicolog\u00eda de los personajes, y la construcci\u00f3n de un universo ficticio (Macondo) que funciona como alegor\u00eda de toda Am\u00e9rica Latina. Sin embargo, algunos cr\u00edticos como Mario Vargas Llosa han cuestionado si el realismo m\u00e1gico no representa una forma de exotizaci\u00f3n de la realidad latinoamericana, reduci\u00e9ndola a elementos folcl\u00f3ricos en lugar de abordar sus complejidades pol\u00edticas y sociales. Otros estudiosos argumentan que precisamente la fus\u00f3n de lo m\u00e1gico y lo real permite una cr\u00edtica m\u00e1s profunda de las estructuras de poder y las din\u00e1micas sociales de la regi\u00f3n.`,
        question: '\u00bfQu\u00e9 posici\u00f3n toma el texto sobre el debate cr\u00edtico del realismo m\u00e1gico?',
        options: ['Presenta cr\u00edticas y defensas sin tomar postura definitiva', 'Defiende solo la posici\u00f3n de Vargas Llosa', 'Rechaza completamente el movimiento', 'Considera que el debate no es relevante'],
        correct: 0,
        explanation: { correct: 'Presenta tanto cr\u00edticas como defensas sin tomar postura definitiva.', wrongs: ['No defiende solo a Vargas Llosa.', 'No rechaza el realismo m\u00e1gico.', 'Considera el debate relevante.'] }
    },
);


